language: python

python:
  - '3.4'

install:
  - pip install coveralls
  - pip install pycodestyle
  - pip install jsonschema

before_script:
  - pycodestyle --ignore=E203 openpdi

script:
 - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coverage run -m  --source openpdi unittest discover; fi

after_success:
  - coveralls
